version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: library
    ports:
      - 3306:3306
    volumes:
      - './.data/db:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: library_db